# Page settings

baseURL = "https://ttwu.github.io/"
languageCode = "en"
title = "Hi, I'm Tingting Wu"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "docs"





[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Tingting Wu"
        tagline = "PhD Student"
        avatar = "ttwu.jpg"







    [params.contact]
        enable = true
        location = "Harbin"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:ttwu@ir.hit.edu.cn"
        text = "Mail"
        [[params.contact.list]]
        icon = "fab fa-google"
        url = "https://scholar.google.com/citations?user=UM5QuBkAAAAJ&hl=zh-CN"
        text = "Google Scholar"






    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Language"
        [[params.skills.list.items]]
        details = "Python/C++/C"      

        [[params.skills.list]]
        title = "Platform"
        [[params.skills.list.items]]
        details = "Pytorch"

 







    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD - Computer Science"
        university = "Harbin Institute of Technology"
        dates = "2020 - Present"
        [[params.education.list]]
        degree = "Master - Information and Communication Engineering"
        university = "University of Science and Technology of China"
        dates = "2012 - 2015"
        [[params.education.list]]
        degree = "Bachelor - Communication Engineering"
        university = "Harbin Institute of Technology"
        dates = "2008 - 2012"






    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "2021 Best Paper Award for IEEE Multimedia"
        body = "IEEE Computer Society Publications Board"
        date = "2021"




    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "Chinese"
        [[params.languages.list]]
        name = "English"









    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Machine Learning"
        [[params.interests.list]]
        name = "Label-noise Learning"
        [[params.interests.list]]
        name = "Natural Language Processing (NLP) Applications"









    [params.summary]
        enable = true
        text = "I'm a Ph.D. student in Research Center for Social Computing and Information Retrieval(SCIR), at Harbin Institute of Technology (HIT, China). I am co-advised by Prof. Bing Qin and Prof. Yanyan Zhao. My research interests include multimodal sentiment analysis and large language model."








    [params.experience]
        enable = false

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."





    [params.information]
        enable = true


        [[params.information.list]]

        title = "STGN: an Implicit Regularization Method for Learning with Noisy Labels in Natural Language Processing."
        name = "Tingting Wu, Xiao Ding, Minji Tang, Hao Zhang, , Bing Qin, Ting Liu"
        publisher = "EMNLP 2022"
        href = "https://aclanthology.org/2022.emnlp-main.515.pdf"
    
        details = "We propose a novel stochastic tailor-made gradient noise (STGN), mitigating the effect of inherent label noise by introducing tailor-made benign noise for each sample. Specifically, we investigate multiple principles to precisely and stably discriminate correct samples from incorrect ones and thus apply different intensities of perturbation to them. A detailed theoretical analysis shows that STGN has good properties, beneficial for model generalization. Experiments on three different NLP tasks demonstrate the effectiveness and versatility of STGN. Also, STGN can boost existing robust training methods."

        [[params.information.list]]

        title = "DiscrimLoss: A Universal Loss for Hard Samples and Incorrect Samples Discrimination."
        name = "Tingting Wu, Xiao Ding, Hao Zhang, Jinglong Gao, Minji Tang, Li Du, Bing Qin, Ting Liu"
        publisher = "IEEE Transactions on Multimedia"
        href = "https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10167857"

        details = "We propose to append a novel loss function DiscrimLoss on top of the existing task loss. Its main effect is to automatically and stably estimate the importance of easy samples and difficult samples (including hard and incorrect samples) at the early stages of training to improve the model performance. Then, during the following stages, DiscrimLoss is dedicated to discriminating between hard and incorrect samples to improve the model generalization. Such a training strategy can be formulated dynamically in a self-supervised manner, effectively mimicking the main principle of curriculum learning. Experiments on image classification, image regression, text sequence regression, and event relation reasoning demonstrate the versatility and effectiveness of our method, particularly in the presence of diversified noise levels."

        [[params.information.list]]
        title = "NoisywikiHow: A Benchmark for Learning with Real-world Noisy Labels in Natural Language Processing."
        name = "Tingting Wu, Xiao Ding, Minji Tang, Hao Zhang, Bing Qin, Ting Liu"
        publisher = "Findings of ACL 2023"
        href = "https://aclanthology.org/2023.findings-acl.299.pdf"

        details = "We contribute NoisywikiHow, the largest NLP benchmark built with minimal supervision. Specifically, inspired by human cognition, we explicitly construct multiple sources of label noise to imitate human errors throughout the annotation, replicating realworld noise, whose corruption is affected by both ground-truth labels and instances. Moreover, we provide a variety of noise levels to support controlled experiments on noisy data, enabling us to evaluate LNL methods systematically and comprehensively. After that, we conduct extensive multi-dimensional experiments on a broad range of LNL methods, obtaining new and intriguing findings."



    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/ttwu"
        title = "ttwu"
 





